# Generated by Django 4.2 on 2025-09-25 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantEmpApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='shop_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
