# Generated by Django 4.2 on 2025-09-26 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantEmpApp', '0002_employee_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
