# Generated by Django 4.2 on 2025-10-07 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantEmpApp', '0003_employee_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveBigIntegerField()),
                ('category', models.CharField(blank=True, max_length=50, null=True)),
                ('image_path', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
    ]
