# Generated by Django 4.2 on 2025-10-07 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RestaurantEmpApp', '0004_food'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='shop_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
